name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  run-spider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install -r requirements-scrapy.txt
      - run: scrapy crawl prixpellets
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/monthly_prices.csv
          git diff-index --quiet HEAD || git commit -m "Update CSV data - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-plots:
    runs-on: ubuntu-latest
    needs: run-spider
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install -r requirements-plot.txt
      - run: python plot.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/images
          git diff-index --quiet HEAD || git commit -m "Update plots - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
