name: Update Plots

on:
  push:
    paths:
      - 'data/monthly_prices.csv'

jobs:
  update-plots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install -r requirements-plot.txt
      - run: python plot.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/images
          git diff --quiet || git commit -m "Update plots - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
